name: Weather App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate files
        run: |
          test -f index.html
          test -f script.js
          test -f style.css

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t weather-app .

      - name: Run Docker container (test)
        run: docker run -d -p 8080:80 weather-app