name: Deploy Weather App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/weather-app-ci-cd

            git pull origin main

            docker stop weather-container || true
            docker rm weather-container || true

            docker build -t weather-app .

            docker run -d \
              --name weather-container \
              -p 80:80 \
              weather-app